### ISSUE TITLE
报表新建成功后，查看报错

### ISSUE THREAD

**Issue by blue20080** [baidu/BIPlatform#14]
[2017-12-21 17:08:21.144] boot - 26986  INFO [http-nio-8090-exec-9] --- MiniCubeSqlConnection: begin execute query with queryrouter 
[2017-12-21 17:08:21.145] boot - 26986  INFO [http-nio-8090-exec-9] --- MiniCubeSqlConnection: {"cube":{"dimensions":{"salary_DEPARTMENT_ID":{"tableName":"salary","type":"STANDARD_DIMENSION","levels":{"DEPARTMENT_ID":{"source":"DEPARTMENT_ID","type":"REGULAR","dimTable":"salary","factTableColumn":"EMPLOYEE_ID","id":"748b136f0ae28cf083cebfb31c64a437","name":"DEPARTMENT_ID","caption":"DEPARTMENT_ID","visible":true,"primaryKey":"EMPLOYEE_ID"}},"facttableColumn":"EMPLOYEE_ID","facttableCaption":"EMPLOYEE_ID","id":"4e99cf293671711c576bd4c330b4f673","name":"salary_DEPARTMENT_ID","caption":"DEPARTMENT_ID","visible":true,"primaryKey":"EMPLOYEE_ID"}},"measures":{"FIRST_NAME":{"aggregator":"SUM","type":"COMMON","define":"FIRST_NAME","id":"f54370d260a1ea3da68de3ae8cb8f61f","name":"FIRST_NAME","caption":"FIRST_NAME","visible":true}},"enableCache":true,"source":"employee","mutilple":false,"productLine":"github","id":"18d33eaf6f718c873dc61e64984e2f39_9672799783e6417b68071841ad666d5c","name":"18d33eaf6f718c873dc61e64984e2f39","visible":true},"axisMetas":{"ROW":{"crossjoinDims":["salary_DEPARTMENT_ID"],"axisType":"ROW"},"COLUMN":{"queryMeasures":["FIRST_NAME"],"queryItemsOrder":["[Measure].[FIRST_NAME]"],"axisType":"COLUMN"},"FILTER":{"axisType":"FILTER"}},"queryConditions":{"salary_DEPARTMENT_ID":{"queryDataNodes":[],"metaName":"salary_DEPARTMENT_ID","metaType":"Dimension","memberSortType":"ASC"}},"requestParams":{"_rbk":"github","Cookie":"_ga=GA1.1.737983121.1513314857; metabase.SESSION_ID=c7948376-4280-4075-b8fa-fdad5ec0c8a8; uniqueFlag=8c3915eb37b0145cd1e8194acb020c74; RANDOMVALIDATECODEKEY=RANDOMVALIDATECODEKEY; biplatform_productline=VhzO4t6QAybS0RZGjiqXig%3D%3D","_cltime":"1513847301122","_cltimezone":"-480","componentId":"9672799783e6417b68071841ad666d5c","reportId":"aafd7f6703e284ef9a8fd317040a9f9e","uniqueFlag":"8c3915eb37b0145cd1e8194acb020c74","_V_SRC":"PROD","_ga":"GA1.1.737983121.1513314857","metabase.SESSION_ID":"c7948376-4280-4075-b8fa-fdad5ec0c8a8","token":"VhzO4t6QAybS0RZGjiqXig=="},"sortRecord":{"sortType":"DESC","sortColumnUniquename":"[Measure].[FIRST_NAME]","recordSize":500},"cubeId":"18d33eaf6f718c873dc61e64984e2f39","dataSourceInfo":{"dataSourceKey":"e43660b657a8a3828ff552d751ec968d","hosts":["192.168.8.101:3306"],"jdbcUrls":["jdbc:mysql://192.168.8.101:3306/foodmart2?useUniCode=true&noAccessToProcedureBodies=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8"],"username":"root","password":"u%2F9fzYMDFmixjTQU85Mczw%3D%3D","instanceName":"foodmart2","isDBProxy":false,"dbPoolInfo":{},"dataBase":"MYSQL","productLine":"github","dataSourceType":"SQL"},"useCache":true,"queryConditionLimit":{"warnningConditionSize":50000,"warningAtOverFlow":false},"needSummary":false,"isUseIndex":true,"filterBlank":false,"queryId":"155244872790987"}
[2017-12-21 17:08:21.145] boot - 26986  INFO [http-nio-8090-exec-9] --- HttpRequest: start to send post:http://[127.0.0.1:8080]/queryrouter/query
[2017-12-21 17:08:21.145] boot - 26986  INFO [http-nio-8090-exec-9] --- HttpRequest: post url is : http://127.0.0.1:8080/queryrouter/query
[2017-12-21 17:08:21.146] boot - 26986  INFO [http-nio-8090-exec-9] --- HttpRequest: [INFO] --- --- execute query with client org.apache.http.impl.client.InternalHttpClient@4c7a3513
[2017-12-21 17:08:21.151] boot - 26986  INFO [http-nio-8090-exec-9] --- HttpRequest: [INFO] response --- --- HttpResponseProxy{HTTP/1.1 405 Method Not Allowed [Server: Apache-Coyote/1.1, Allow: HEAD, GET, Content-Type: application/json;charset=UTF-8, Transfer-Encoding: chunked, Date: Thu, 21 Dec 2017 09:08:21 GMT] ResponseEntityProxy{[Content-Type: application/json;charset=UTF-8,Chunked: true]}}
[2017-12-21 17:08:21.151] boot - 26986  WARN [http-nio-8090-exec-9] --- HttpRequest: Server internal error[405]
java.lang.IllegalStateException: Server internal error[405]
	at com.baidu.rigel.biplatform.ac.util.HttpRequest.processHttpResponse(HttpRequest.java:370)
	at com.baidu.rigel.biplatform.ac.util.HttpRequest.sendPost(HttpRequest.java:300)
	at com.baidu.rigel.biplatform.ac.util.HttpRequest.sendPost(HttpRequest.java:330)
	at com.baidu.rigel.biplatform.ac.query.MiniCubeSqlConnection.query(MiniCubeSqlConnection.java:83)
	at com.baidu.rigel.biplatform.ma.report.service.impl.ReportModelQueryServiceImpl.queryDatasHelper(ReportModelQueryServiceImpl.java:280)
	at com.baidu.rigel.biplatform.ma.report.service.impl.ReportModelQueryServiceImpl.queryDatas(ReportModelQueryServiceImpl.java:230)
	at com.baidu.rigel.biplatform.ma.resource.QueryDataResource.queryArea(QueryDataResource.java:245)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.baidu.rigel.biplatform.ma.resource.filter.UniversalContextSettingFilter.setSessionInfoIntoThread(UniversalContextSettingFilter.java:364)
	at com.baidu.rigel.biplatform.ma.resource.filter.UniversalContextSettingFilter.doFilter(UniversalContextSettingFilter.java:136)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by blue20080** [comment]
Caused by: java.lang.RuntimeException: send post failed[http://[127.0.0.1:8080]/queryrouter/query]. params :[question={"cube":{"d...

自己将 
http://127.0.0.1:8080
http://127.0.0.1:8080/queryrouter
http://127.0.0.1:8080/queryrouter/query
复制到浏览起，
web页面显示:

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Dec 21 17:53:28 CST 2017
There was an unexpected error (type=Not Found, status=404).
No message available

不知是哪里配置有问题，还是其他原因？

**Comment by wangyuxue** [comment]
@blue20080  从错误信息看，应该是你浏览的请求不对。配置完报表之后，需要发布。发布之后有一个url。将那个url复制到浏览器地址栏，可以浏览报表

**Comment by wangyuxue** [comment]
@blue20080 你贴一下：ac.properties的配置

**Comment by blue20080** [comment]
@wangyuxue 
配置文件内容如下：
################################################################################################
#tesseract server address
################################################################################################
server.tesseract.address=http://[127.0.0.1:8080 127.0.0.1:9191]/

**Comment by blue20080** [comment]
报表发布后的URL：
http://localhost:8090/silkroad/reports/aafd7f6703e284ef9a8fd317040a9f9e/report_vm?token=VhzO4t6QAybS0RZGjiqXig%3D%3D&amp;_rbk=github

**Comment by wangyuxue** [comment]
@blue20080 你方便贴一下错误信息么

**Comment by wangyuxue** [comment]
@blue20080 在你的ac.properties中增加配置
server.queryrouter.address=http://[queryrouter服务的地址+端口号]/queryrouter
server.queryrouter.systemcode=report3desinger
server.queryrouter.systemkey=report3desingerkey
